# Generated by Django 3.2 on 2021-04-29 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='person',
            new_name='user',
        ),
    ]
