# Generated by Django 3.2 on 2021-04-29 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0002_rename_person_data_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='protein',
        ),
    ]
