# Generated by Django 3.2 on 2021-04-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0003_remove_data_protein'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='protein',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
