# Generated by Django 3.2 on 2021-04-29 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0004_data_protein'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
